### PR TITLE
Attempt to fix IOException/GOAWAY happening within parseResults()

### LINKED ISSUE #817: [BUG] IOException/GOAWAY happening in parseResults()
**Describe the bug**

While generating tiles with `--fetch-wikidata` following was observed:

```
...
Caused by: java.io.IOException: closed
	at java.net.http/jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream.current(ResponseSubscribers.java:464)
	at java.net.http/jdk.internal.net.http.ResponseSubscribers$HttpResponseInputStream.read(ResponseSubscribers.java:508)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:291)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:347)
	at java.base/java.io.BufferedInputStream.implRead(BufferedInputStream.java:420)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:399)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._loadMore(UTF8StreamJsonParser.java:258)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.parseEscapedName(UTF8StreamJsonParser.java:2102)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.slowParseName(UTF8StreamJsonParser.java:2010)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._parseName(UTF8StreamJsonParser.java:1798)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser.nextFieldName(UTF8StreamJsonParser.java:1081)
	at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer._deserializeContainerNoRecursion(JsonNodeDeserializer.java:536)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:100)
	at com.fasterxml.jackson.databind.deser.std.JsonNodeDeserializer.deserialize(JsonNodeDeserializer.java:25)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readTreeAndClose(ObjectMapper.java:4867)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3199)
	at com.onthegomap.planetiler.util.Wikidata.parseResults(Wikidata.java:92)
	at com.onthegomap.planetiler.util.Wikidata.queryWikidata(Wikidata.java:379)
	at com.onthegomap.planetiler.util.Wikidata.flush(Wikidata.java:314)
	... 9 more
Caused by: java.io.IOException: /<IP of our server>:33120: GOAWAY received
	at java.net.http/jdk.internal.net.http.Http2Connection.handleGoAway(Http2Connection.java:1166)
...
```

Error was observed several times roughly a week ago, but then never again so far.

**To Reproduce**

While not able to reproduce the issue with WikiData server(s) and not willing to pound on them too much I've tried a mock:

1. Setup a dummy nginx powered WikiData API mock with dummy JSON response implemented (as static file but allowing POST), HTTP/2 enabled and `http2_max_requests 25;` setting
2. Adjust Planetiler to use a dummy nginx mock server
3. Run Planetiler with `--fetch-wikidata`
4. See the error

Main problem is, that I failed to trigger the error within `parseResults()` since I'm not sure about what were the conditions on servers:

- server running Planetiler, e.g. mainly CPU and network load
- WikiData server, e.g. again mainly CPU and network load, possibly scheduled or unscheduled reboot, etc.

**Expected behavior**

Planetiler is handling all `IOException` by retrying the requests, that is expected behavior.

**Screenshots**

N/A

**Environment (please complete the following information):**

- Hardware: some server
- OS: Linux/Ubuntu
- Java version and distribution: 21 shipped by Ubuntu
- Maven version: N/A (e.g. Planetiler compiled elsewhere)

**Additional context**

Searching around I found this: https://nuvalence.io/insights/lessons-learned-investigating-goaways-in-grpc-apis/ which may implicate `http2_max_requests` setting as a factor in this. Based on that I've tried to trigger GOAWAY with nginx. Also `query.wikidata.org` seems to be running on or behind nginx.

### PR DESCRIPTION
**Pull request by phanecak-maptiler**
This should fix #817 by moving `parseResults()` into the the retry loop, into `try+catch` statement. Retries after `GOAWAY` are done after 5 seconds (configurable with `http_retry_wait`) to give server some room to recover.

I've tested the code, but I was unable to fully reproduce GOAWAY inside `parseResults()` hence I'm not sure the fix is fully effective.

### CODE REVIEW

File: planetiler-core/src/main/java/com/onthegomap/planetiler/util/Wikidata.java [hunk 1]
```diff
@@ -300,10 +300,15 @@ private LongObjectMap<Map<String, String>> queryWikidata(List<Long> qidsToFetch)
...
-        response = client.send(request);
+        var response = client.send(request);
+        if (response != null) {
+          try (var bis = new BufferedInputStream(response)) {
+            result = parseResults(bis);
+          }
+        }
       } catch (IOException e) {
         boolean lastTry = i == config.httpRetries();
         if (!lastTry) {
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/util/Wikidata.java:314]: While we're at it, can we add a sleep (maybe 5-10s?) here to back off on the server a bit when there's an error. The GOAWAY response makes it sound like the server wants us to slow down.

File: planetiler-core/src/main/java/com/onthegomap/planetiler/util/Wikidata.java [hunk 2]
```diff
@@ -300,10 +300,15 @@ private LongObjectMap<Map<String, String>> queryWikidata(List<Long> qidsToFetch)
...
-    InputStream response = null;
-    for (int i = 0; i <= config.httpRetries() && response == null; i++) {
+    LongObjectMap<Map<String, String>> result = null;
+    for (int i = 0; i <= config.httpRetries() && result == null; i++) {
       try {
-        response = client.send(request);
+        var response = client.send(request);
+        if (response != null) {
+          try (var bis = new BufferedInputStream(response)) {
+            result = parseResults(bis);
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/util/Wikidata.java:309]: 👍

File: planetiler-core/src/main/java/com/onthegomap/planetiler/util/Wikidata.java (hunk 1 above)
Comment (phanecak-maptiler) [reply planetiler-core/src/main/java/com/onthegomap/planetiler/util/Wikidata.java:314]: Adjusted.

File: planetiler-core/src/main/java/com/onthegomap/planetiler/config/PlanetilerConfig.java [hunk 3]
```diff
@@ -166,6 +167,7 @@ public static PlanetilerConfig from(Arguments arguments) {
         "Planetiler downloader (https://github.com/onthegomap/planetiler)"),
       arguments.getDuration("http_timeout", "Timeout to use when downloading files over HTTP", "30s"),
       arguments.getInteger("http_retries", "Retries to use when downloading files over HTTP", 1),
+      arguments.getLong("http_retry_wait", "How long (in milliseconds) to wait before retrying HTTP request", 5_000),
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/config/PlanetilerConfig.java:170]: Thanks for adding this as a config option! Let's use the `getDuration` helper though which handles unit conversions.

File: planetiler-core/src/main/java/com/onthegomap/planetiler/util/Wikidata.java [hunk 4]
```diff
@@ -312,13 +317,19 @@ private LongObjectMap<Map<String, String>> queryWikidata(List<Long> qidsToFetch)
...
           throw e;
         }
+        if (e.getMessage() != null && e.getMessage().contains("GOAWAY")) {
+          try {
+            LOGGER.debug("GOAWAY received, waiting {} ms to give server some room", config.httpRetryWait());
+            Thread.sleep(config.httpRetryWait());
+          } catch (InterruptedException e2) {
+            Thread.currentThread().interrupt();
+          }
+        }
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/util/Wikidata.java:327]: Can we just do the wait in all cases, in case there's another kind of "please back off" response that looks slightly different?

Also this method can throw `InterruptedException` is there a reason we wouldn't want to let that propagate?

File: planetiler-core/src/main/java/com/onthegomap/planetiler/config/PlanetilerConfig.java (hunk 3 above)
Comment (phanecak-maptiler) [reply planetiler-core/src/main/java/com/onthegomap/planetiler/config/PlanetilerConfig.java:170]: Ah, overlooked that, thanks. Adjusted.

File: planetiler-core/src/main/java/com/onthegomap/planetiler/config/PlanetilerConfig.java [hunk 5]
```diff
@@ -166,6 +167,7 @@ public static PlanetilerConfig from(Arguments arguments) {
         "Planetiler downloader (https://github.com/onthegomap/planetiler)"),
       arguments.getDuration("http_timeout", "Timeout to use when downloading files over HTTP", "30s"),
       arguments.getInteger("http_retries", "Retries to use when downloading files over HTTP", 1),
+      arguments.getDuration("http_retry_wait", "How long (in milliseconds) to wait before retrying HTTP request", "5s"),
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/config/PlanetilerConfig.java:170]: Looks good! Can you just remove "in milliseconds" now?

Comment (phanecak-maptiler) [reply planetiler-core/src/main/java/com/onthegomap/planetiler/config/PlanetilerConfig.java]: Yup, sorry. You're quick. Thanks.
