### PR TITLE
Fix node location OOM error and hang (#1464)

### LINKED ISSUE #1464: Planetiler execution is very long and never ends
### Here is the full command I have run :

java -Xmx15g -jar planetiler.jar --extra=background=world_background.geojson --area=planet --bounds=planet --fetch_wikidata --output=planet-osm.mbtiles --nodemap_type=array --storage=mmap --osm_lazy_reads=false --process_threads=10 --write_threads=5 --feature_read_threads=10 --force --exclude_layers=aerodrome_label,housenumber,park,place,poi,transportation_name,water_name

### And here is the content of file world_background.geojson :

{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "id": 1,
        "kind": "background"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [-180.0, -85.05112878],
            [ 180.0, -85.05112878],
            [ 180.0,  85.05112878],
            [-180.0,  85.05112878],
            [-180.0, -85.05112878]
          ]
        ]
      }
    }
  ]
}

Planetiler has been running for 53 hours and is not terminated.
The lines below is an extract of what I get in cmd.exe. Every ten seconds, the same line is displayed :

53:37:16 INF [osm_pass1] -  nodes: [ 3,1B    0/s ] 34G   ways: [    0    0/s ] rels: [    0    0/s ] blocks: [  11k    0/s ]
    cpus: 0 gc: 0┬á% heap: 12G/16G direct: 1,5G postGC: 8,8G hppc:  928
    read(0┬á%) ->   (55/82) -> process(0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á%)
53:37:26 INF [osm_pass1] -  nodes: [ 3,1B    0/s ] 34G   ways: [    0    0/s ] rels: [    0    0/s ] blocks: [  11k    0/s ]
    cpus: 0 gc: 0┬á% heap: 12G/16G direct: 1,5G postGC: 8,8G hppc:  928
    read(0┬á%) ->   (55/82) -> process(0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á%)
53:37:36 INF [osm_pass1] -  nodes: [ 3,1B    0/s ] 34G   ways: [    0    0/s ] rels: [    0    0/s ] blocks: [  11k    0/s ]
    cpus: 0 gc: 0┬á% heap: 12G/16G direct: 1,5G postGC: 8,8G hppc:  928
    read(0┬á%) ->   (55/82) -> process(0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á%)
53:37:46 INF [osm_pass1] -  nodes: [ 3,1B    0/s ] 34G   ways: [    0    0/s ] rels: [    0    0/s ] blocks: [  11k    0/s ]
    cpus: 0 gc: 0┬á% heap: 12G/16G direct: 1,5G postGC: 8,8G hppc:  928
    read(0┬á%) ->   (55/82) -> process(0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á%)
53:37:56 INF [osm_pass1] -  nodes: [ 3,1B    0/s ] 34G   ways: [    0    0/s ] rels: [    0    0/s ] blocks: [  11k    0/s ]
    cpus: 0 gc: 0┬á% heap: 12G/16G direct: 1,5G postGC: 8,8G hppc:  928
    read(0┬á%) ->   (55/82) -> process(0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á%)
53:38:06 INF [osm_pass1] -  nodes: [ 3,1B    0/s ] 34G   ways: [    0    0/s ] rels: [    0    0/s ] blocks: [  11k    0/s ]
    cpus: 0 gc: 0┬á% heap: 12G/16G direct: 1,5G postGC: 8,8G hppc:  928
    read(0┬á%) ->   (55/82) -> process(0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á%)
53:38:16 INF [osm_pass1] -  nodes: [ 3,1B    0/s ] 34G   ways: [    0    0/s ] rels: [    0    0/s ] blocks: [  11k    0/s ]
    cpus: 0 gc: 0┬á% heap: 12G/16G direct: 1,5G postGC: 8,8G hppc:  928
    read(0┬á%) ->   (55/82) -> process(0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á% 0┬á%)

What worries me is that nothing happens in output file nor in tmp files :
 - planet-osm.mbtiles has 4kb size ;
 - data/tmp/node.db is 33Gb size ;
 - data/tmp/feature.db folder is 9Gb size ;
 - and the last modification date of all these files was 2 days ago ;

So I'll kill it, but I don't understand what happens.

### PR DESCRIPTION
**Pull request by msbarry**
Fix a race deadlock condition that can happen when `--nodemap-type=array --storage=mmap`  are used together and an exception gets thrown during pass1 when processing nodes. Also fixed the specific exception people were seeing in #1464 by allocating smalller chunks of memory.

Fixes #1464

### CODE REVIEW

File: planetiler-core/src/main/java/com/onthegomap/planetiler/collection/ArrayLongLongMapMmap.java [hunk 1]
```diff
@@ -44,8 +44,8 @@ class ArrayLongLongMapMmap implements LongLongMap.ParallelWrites {
    * TODO: extract maintaining segments list into a separate utility?
    */
 
-  // 128MB per chunk
-  private static final int DEFAULT_SEGMENT_BITS = 27;
+  // 16MB per chunk
+  private static final int DEFAULT_SEGMENT_BITS = 24;
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/collection/ArrayLongLongMapMmap.java]: this was the culprit - trying to allocate slabs of memory that were too big and the JVM couldn't find space for them.
