### PR TITLE
#1541 Fix z16 tile bugs

### LINKED ISSUE #1541: [BUG] Zoom 16 tile encoding: signed overflow in TiledGeometry and FeatureGroup sort key corruption
**Describe the bug**

The zoom 16 support commit (`1fc95a26`) introduces two related issues in tile ID encoding and sort key handling. A third related issue (sort key range reduction with assert-only validation) was already reported in #398 and is now exacerbated by the SORT_KEY_BITS change from 23 to 22.

**Bug 1 (Critical): `TiledGeometry.encode()` int-to-long sign extension causes silent tile loss**

`encode()` at `TiledGeometry.java:808` returns `int`. At zoom 16, `maxTilesAtThisZoom = 65536`. For any tile column `x >= 32768`, the expression `65536 * x` exceeds `Integer.MAX_VALUE` and wraps to a negative `int`.

At line 302, the result is assigned to `long colStart`, which sign-extends the negative int (e.g., `x=32768` → int `-2147483648` → long `-2147483648L`). `RoaringBitmap.addOffset(yRanges.bitmap(), colStart)` then applies a negative offset, causing all y-range values to underflow and be silently dropped.

**Impact:** All interior (filled) tiles for polygon columns with `x >= 32768` at z16 are lost from the `CoveredTiles` bitmap. When used with `--bounds` or `--polygon`, tiles in roughly the eastern half of the world at z16 are silently excluded.

**Fix:** `long colStart = Integer.toUnsignedLong(encode(...))` — matching the pattern already used on lines 784 and 802.

**Bug 2 (High): `FeatureGroup.encodeKey()` sets the sign bit, breaking sort order**

`encodeKey()` computes `tile << (64 - TILE_ID_BITS)` which is `tile << 31`. At z16, tile IDs can exceed `2^32`, which sets bit 63 (the sign bit) of the packed key. `SortableFeature.compareTo()` uses signed `long` comparison (`key < o.key`), so approximately one-third of z16 tiles sort before all z0–z15 tiles.

**Impact:** Tile iteration order is wrong for high z16 tiles. PMTiles output loses clustered ordering, and any order-sensitive writer/reader logic sees tiles out of sequence.

**Note on sort key range:** The SORT_KEY_BITS reduction from 23 to 22 further exacerbates the existing issue reported in #398 — sort keys that were valid before are now silently truncated at runtime (assert-only validation).

**To Reproduce**

For Bug 1:
1. Create a polygon geometry that spans tiles with `x >= 32768` at zoom 16
2. Run with `--bounds` or `--polygon` set
3. Observe that interior tiles in the eastern half are missing from output

For Bug 2:
1. Generate tiles at zoom 16 with tile IDs exceeding `2^32`
2. Check sort order of output features — high z16 tiles appear before z0

**Expected behavior**

- Bug 1: All z16 tiles should be present regardless of x coordinate
- Bug 2: Features should be sorted in correct tile order across all zoom levels

**Environment**

- Code review of commit `1fc95a26` (support zoom 16)
- Found via static analysis with multiple AI code review tools (Claude, GPT-5.4, Gemini)
- Not yet verified at runtime

### PR DESCRIPTION
**Pull request by smellman**
Prevent int overflow in TiledGeometry.encode and use unsigned long comparison for correct sort order.

# Summary

To fix #1541

~Bug 1 — TiledGeometry encode overflow (TiledGeometry.java):~
~- encode() returns int, which overflows for x >= 32768 at z16 (65536 * 32768 = 2^31)~
~- Fix: Integer.toUnsignedLong(encode(...)) prevents sign extension to negative long~

Bug 2 — Sort order with sign bit (multiple files):
  - SortableFeature.compareTo(): Changed Long.compare → Long.compareUnsigned
  - LongMerger.lessThan(): Changed ak < bk → Long.compareUnsigned(ak, bk) < 0, sentinel Long.MAX_VALUE → -1L (unsigned max)
  - ArrayLongMinHeap: Added configurable unsigned mode (boolean flag) so existing signed-comparison users aren't affected
  - LongMinHeap.newUnsignedArrayHeap(): New factory method used by KWayMerge

Regression tests added:
~- TiledGeometryTest.testPolygonZoom16HighXCoordinate — verifies Bug 1 fix~
  - FeatureGroupTest.testZ16HighTileIdsSortAfterLowerZooms — verifies Bug 2 fix

# co-author

Claude Code

### CODE REVIEW

File: planetiler-core/src/main/java/com/onthegomap/planetiler/render/TiledGeometry.java [hunk 1]
```diff
@@ -299,7 +299,7 @@ public CoveredTiles getCoveredTiles() {
     }
     if (filledRanges != null) {
       for (var entry : filledRanges.entrySet()) {
-        long colStart = encode(maxTilesAtThisZoom, entry.getKey(), 0);
+        long colStart = Integer.toUnsignedLong(encode(maxTilesAtThisZoom, entry.getKey(), 0));
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/render/TiledGeometry.java]: Verify this is actually needed for the test to pass

Comment (smellman) [reply planetiler-core/src/main/java/com/onthegomap/planetiler/render/TiledGeometry.java]: @msbarry Thank you, you are right. I verified that RoaringBitmap.addOffset wraps correctly with signed/unsigned offsets (they are congruent mod 2^32), so Integer.toUnsignedLong is not needed here. Reverting.

Comment (msbarry) [reply planetiler-core/src/main/java/com/onthegomap/planetiler/render/TiledGeometry.java]: Thanks! If anything a comment might help so no one thinks it's a bug in the future.

File: planetiler-core/src/test/java/com/onthegomap/planetiler/collection/FeatureGroupTest.java [hunk 2]
```diff
@@ -438,11 +438,42 @@ void testEncodeLongKeyOrdering(
...
-      FeatureGroup.encodeKey(tileA, layerA, sortKeyA, hasGroupA) < FeatureGroup.encodeKey(tileB, layerB, sortKeyB,
-        hasGroupB)
+      Long.compareUnsigned(
+        FeatureGroup.encodeKey(tileA, layerA, sortKeyA, hasGroupA),
+        FeatureGroup.encodeKey(tileB, layerB, sortKeyB, hasGroupB)
+      ) < 0
     );
   }
 
+  @Test
```
Comment (msbarry) [inline planetiler-core/src/test/java/com/onthegomap/planetiler/collection/FeatureGroupTest.java:448]: Thanks for updated this, can you also update MinHeapTest, LongMergerTest and add a PlanetilerTest case that verifies this end to end?

File: planetiler-core/src/main/java/com/onthegomap/planetiler/collection/LongMerger.java [hunk 3]
```diff
@@ -38,7 +38,7 @@ private static class TwoWayMerge<T extends HasLongSortKey> implements Iterator<T
 
     private final Comparator<T> tieBreaker;
     T a, b;
-    long ak = Long.MAX_VALUE, bk = Long.MAX_VALUE;
+    long ak = -1L, bk = -1L;
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/collection/LongMerger.java]: Can you replace all -1L with reference to a constant MAX_UNSIGNED_LONG?

File: planetiler-core/src/main/java/com/onthegomap/planetiler/collection/ArrayLongMinHeap.java [hunk 4]
```diff
@@ -163,10 +169,9 @@ private void percolateUp(int pos) {
     }
     final int id = posToId[pos];
     final long val = posToValue[pos];
-    // the finish condition (index==0) is covered here automatically because we set vals[0]=-inf
     int parent;
     long parentValue;
-    while (compareIdPos(val, parentValue = posToValue[parent = parent(pos)], id, parent) < 0) {
+    while (pos > 1 && compareIdPos(val, parentValue = posToValue[parent = parent(pos)], id, parent) < 0) {
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/collection/ArrayLongMinHeap.java:174]: why is this needed now?

File: planetiler-core/src/test/java/com/onthegomap/planetiler/collection/FeatureGroupTest.java (hunk 2 above)
Comment (smellman) [reply planetiler-core/src/test/java/com/onthegomap/planetiler/collection/FeatureGroupTest.java:448]: I add tests for MinHeapTest, LongMergerTest, and PlanetilerTests.

File: planetiler-core/src/main/java/com/onthegomap/planetiler/collection/LongMerger.java (hunk 3 above)
Comment (smellman) [reply planetiler-core/src/main/java/com/onthegomap/planetiler/collection/LongMerger.java]: I used MAX_UNSIGNED_LONG since the sentinel is a long value (-1L = 0xFFFFFFFFFFFFFFFFL). Did you mean MAX_UNSIGNED_LONG, or do you prefer a different name?

**Comment by smellman** [comment]
@msbarry CI failed in download https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip , can you re-run this job?

File: planetiler-core/src/main/java/com/onthegomap/planetiler/collection/LongMerger.java [hunk 5]
```diff
@@ -63,16 +66,16 @@ public boolean hasNext() {
...
         if (inputA.hasNext()) {
           a = inputA.next();
           ak = a.key();
         } else {
           a = null;
-          ak = Long.MAX_VALUE;
+          ak = MAX_UNSIGNED_LONG;
         }
-      } else if (bk == Long.MAX_VALUE) {
+      } else if (b == null) {
```
Comment (msbarry) [inline planetiler-core/src/main/java/com/onthegomap/planetiler/collection/LongMerger.java:78]: It seems like this should be `bk == MAX_UNSIGNED_LONG` in case the input interators contain null values (same below)

File: planetiler-core/src/test/java/com/onthegomap/planetiler/collection/FeatureGroupTest.java (hunk 2 above)
Comment (msbarry) [reply planetiler-core/src/test/java/com/onthegomap/planetiler/collection/FeatureGroupTest.java:448]: Thanks!

File: planetiler-core/src/test/java/com/onthegomap/planetiler/collection/MinHeapTest.java [hunk 6]
```diff
@@ -59,6 +59,54 @@ void create(int capacity, IntBinaryOperator tieBreaker) {
     }
   }
 
+  static class UnsignedLongMinHeapTest {
```
Comment (msbarry) [inline planetiler-core/src/test/java/com/onthegomap/planetiler/collection/MinHeapTest.java]: Can we make this extend MinHeapTest so that it runs all of the standard tests against unsigned min heap implementation?

File: planetiler-core/src/test/java/com/onthegomap/planetiler/PlanetilerTests.java [hunk 7]
```diff
@@ -1066,6 +1066,32 @@ void testZ16Fill() throws Exception {
...
+      (in, features) -> features.point("layer")
+        .setZoomRange(16, 16)
+        .inheritAttrFromSource("attr")
+    );
+
+    assertSubmap(Map.of(
+      TileCoord.ofXYZ(50_000, 500, 16), List.of(
+        feature(newPoint(128, 128), Map.of("attr", "value"))
+      )
+    ), results.tiles);
```
Comment (msbarry) [inline planetiler-core/src/test/java/com/onthegomap/planetiler/PlanetilerTests.java]: This ensures that we output it correctly, but I'm wondering if there's a way to assert that the z16 tile appears in the output archive before a lower zoom tile?

File: planetiler-core/src/main/java/com/onthegomap/planetiler/collection/ArrayLongMinHeap.java (hunk 4 above)
Comment (smellman) [reply planetiler-core/src/main/java/com/onthegomap/planetiler/collection/ArrayLongMinHeap.java:174]: The old compareIdPos had a special val1 != Long.MIN_VALUE guard that made the sentinel at position 0 always terminate the loop. The new comparison methods use plain Long.compare/Long.compareUnsigned without that special case, so the explicit pos > 1 bounds check is needed to replace it.

File: planetiler-core/src/main/java/com/onthegomap/planetiler/collection/LongMerger.java (hunk 5 above)
Comment (smellman) [reply planetiler-core/src/main/java/com/onthegomap/planetiler/collection/LongMerger.java:78]: b == null is intentional — MAX_UNSIGNED_LONG is a valid key value (when all bits of encodeKey are set), so bk == MAX_UNSIGNED_LONG would incorrectly throw NoSuchElementException for a real item. The test testMergeUnsignedKeyOrder covers this case with key=-1L. Null values from iterators are not a concern here since they would NPE at b.key() during advancement before reaching this check.

File: planetiler-core/src/test/java/com/onthegomap/planetiler/collection/MinHeapTest.java (hunk 6 above)
Comment (smellman) [reply planetiler-core/src/test/java/com/onthegomap/planetiler/collection/MinHeapTest.java]: I update test code.

File: planetiler-core/src/test/java/com/onthegomap/planetiler/PlanetilerTests.java (hunk 7 above)
Comment (smellman) [reply planetiler-core/src/test/java/com/onthegomap/planetiler/PlanetilerTests.java]: Added a testZ16HighTileIteratesAfterLowerZoomTiles test in FeatureGroupTest that puts features at both z0 and z16 (x=50000) into a  FeatureGroup, then iterates to verify z0 appears before the z16 high tile. Also updated the PlanetilerTests case to output both z0 and z16 tiles and assert their relative order in the output.

**Review by msbarry — APPROVED** [review]

**Comment by msbarry** [comment]
Looks great, thanks for the fixes @smellman !
